version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.backend
    container_name: backend_container
    ports:
      - "85:80"
    volumes:
      - ./backend:/var/www/html
    networks:
      - app_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
      args:
        - BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')  # Adicione esta linha para evitar o cache de ARGs
    container_name: frontend_container
    ports:
      - "84:5173"
    volumes:
      - ./frontend:/var/www/app
      - ./frontend:/var/www/html/app/node_modules
    networks:
      - app_network

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql_container
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #   command: --default-authentication-plugin=mysql_native_password
  #   networks:
  #     - app_network

networks:
  app_network:
    driver: bridge
